Repository imashnake0/Animite, pull requests merged in 2022-05, with the labels that each got.

#22 Refactor Home path
  app/src/main/java/com/imashnake/animite/ui/elements/home/MediaSmall.kt
  app/src/main/java/com/imashnake/animite/ui/elements/home/MediaSmallRow.kt
Labels: enhancement

#20 Home
  app/build.gradle.kts
  app/src/main/graphql/com/imashnake/animite/AnimeQuery.graphql
  app/src/main/graphql/com/imashnake/animite/PopularThisSeasonQuery.graphql
  app/src/main/graphql/com/imashnake/animite/TrendingNowQuery.graphql
  app/src/main/java/com/imashnake/animite/data/repos/MediaListRepository.kt
  app/src/main/java/com/imashnake/animite/data/sauce/ApolloMediaListApi.kt
  app/src/main/java/com/imashnake/animite/data/sauce/MediaListApi.kt
  app/src/main/java/com/imashnake/animite/data/sauce/MediaListNetworkSource.kt
  app/src/main/java/com/imashnake/animite/di/NetworkModule.kt
  app/src/main/java/com/imashnake/animite/ui/MainActivity.kt
  app/src/main/java/com/imashnake/animite/ui/elements/Home.kt
  app/src/main/java/com/imashnake/animite/ui/elements/Profile.kt
  app/src/main/java/com/imashnake/animite/ui/elements/RSlash.kt
  app/src/main/java/com/imashnake/animite/ui/elements/home/Home.kt
  app/src/main/java/com/imashnake/animite/ui/elements/home/MediaSmall.kt
  app/src/main/java/com/imashnake/animite/ui/elements/home/MediaSmallRow.kt
  app/src/main/java/com/imashnake/animite/ui/elements/profile/Profile.kt
  app/src/main/java/com/imashnake/animite/ui/elements/rslash/RSlash.kt
  app/src/main/java/com/imashnake/animite/ui/state/HomeUiState.kt
  app/src/main/java/com/imashnake/animite/ui/state/HomeViewModel.kt
  app/src/main/java/com/imashnake/animite/ui/theme/Color.kt
  app/src/main/java/com/imashnake/animite/ui/theme/Shape.kt
  app/src/main/java/com/imashnake/animite/ui/theme/Theme.kt
  app/src/main/java/com/imashnake/animite/ui/theme/Type.kt
  app/src/main/res/drawable/background.png
  app/src/main/res/drawable/home.xml
  app/src/main/res/drawable/rslash.xml
  app/src/main/res/font/manrope_bold.ttf
  app/src/main/res/font/manrope_extrabold.ttf
  app/src/main/res/font/manrope_extralight.ttf
  app/src/main/res/font/manrope_light.ttf
  app/src/main/res/font/manrope_medium.ttf
  app/src/main/res/font/manrope_regular.ttf
  app/src/main/res/font/manrope_semibold.ttf
  versions.properties
Labels: enhancement

#24 Version catalogs
  app/build.gradle.kts
  build.gradle.kts
  custom-version-alias-rules.txt
  gradle/libs.versions.toml
  settings.gradle.kts
  versions.properties
Labels: gradle

#26 Update Compose
  app/build.gradle.kts
  app/src/main/java/com/imashnake/animite/ui/elements/home/MediaSmall.kt
  gradle/libs.versions.toml
Labels: dependencies

#27 Updated Kotlin
  gradle/libs.versions.toml
Labels: dependencies

#28 Updated AGP
  gradle/libs.versions.toml
Labels: dependencies

#29 Targeted API 32
  app/build.gradle.kts
Labels: gradle

#30 Updated Dagger
  gradle/libs.versions.toml
Labels: dependencies

#31 Created version references
  gradle/libs.versions.toml
Labels: gradle

#32 Remove landscape support
  app/src/main/AndroidManifest.xml
Labels: bug

#33 Updated Apollo Kotlin
  gradle/libs.versions.toml
Labels: dependencies
