Repository imashnake0/Animite, pull requests merged in 2024-07, with the labels that each got.

#136 Added Genres to the User's About Tab
  .gitignore
  api/anilist/src/main/graphql/UserQuery.graphql
  api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/AnilistUserRepository.kt
  api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/sanitize/profile/Viewer.kt
  app/src/main/java/com/imashnake/animite/features/home/HomeScreen.kt
  app/src/main/java/com/imashnake/animite/features/media/MediaPage.kt
  app/src/main/java/com/imashnake/animite/features/searchbar/SearchFab.kt
  core/src/main/kotlin/com/imashnake/animite/core/ui/NestedScrollableContent.kt
  core/src/main/kotlin/com/imashnake/animite/core/ui/layouts/BannerLayout.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt
  profile/src/main/res/values/strings.xml
Labels: enhancement

#137 Added Stats to the User's About Tab
  api/anilist/src/main/graphql/UserQuery.graphql
  api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/sanitize/profile/Viewer.kt
  app/src/main/java/com/imashnake/animite/features/media/MediaPage.kt
  core/src/main/kotlin/com/imashnake/animite/core/ui/Stats.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt
  profile/src/main/res/values/strings.xml
Labels: enhancement

#138 Added Media Lists to the User's Anime Tab
  api/anilist/src/main/graphql/MediaListQuery.graphql
  api/anilist/src/main/graphql/UserQuery.graphql
  api/anilist/src/main/graphql/fragments/MediaSmall.graphql
  api/anilist/src/main/graphql/fragments/User.graphql
  api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/AnilistMediaRepository.kt
  api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/AnilistUserRepository.kt
  api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/sanitize/media/Media.kt
  api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/sanitize/profile/Viewer.kt
  api/preferences/src/main/kotlin/com/imashnake/animite/api/preferences/PreferencesRepository.kt
  app/src/main/java/com/imashnake/animite/features/home/HomeScreen.kt
  app/src/main/java/com/imashnake/animite/features/media/MediaPage.kt
  app/src/main/java/com/imashnake/animite/features/searchbar/SearchFrontDrop.kt
  app/src/main/res/values/dimens.xml
  core/src/main/kotlin/com/imashnake/animite/core/ui/MediaSmall.kt
  core/src/main/kotlin/com/imashnake/animite/core/ui/Stats.kt
  core/src/main/res/values/dimens.xml
  profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/ProfileViewModel.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/tabs/About.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Anime.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/tabs/ProfileTabs.kt
Labels: enhancement, feature

#139 Update dependencies
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle.kts
Labels: dependencies, gradle
