Repository imashnake0/Animite, pull requests merged in 2024-12, with the labels that each got.

#225 Replace our material-color-utilities fork with MaterialKolor
  README.md
  app/build.gradle.kts
  app/src/main/kotlin/com/imashnake/animite/dev/ext/ColorSchemeExt.kt
  app/src/main/kotlin/com/imashnake/animite/dev/ext/SchemeExt.kt
  app/src/main/kotlin/com/imashnake/animite/features/media/MediaThemeUtil.kt
  app/src/main/kotlin/com/imashnake/animite/features/theme/Theme.kt
  core/src/main/kotlin/com/imashnake/animite/core/Constants.kt
  gradle/libs.versions.toml
  material-color-utilities/README.md
  material-color-utilities/build.gradle.kts
  material-color-utilities/src/main/AndroidManifest.xml
  material-color-utilities/src/main/kotlin/blend/Blend.kt
  material-color-utilities/src/main/kotlin/common/BiFunction.kt
  material-color-utilities/src/main/kotlin/common/Function.kt
  material-color-utilities/src/main/kotlin/contrast/Contrast.kt
  material-color-utilities/src/main/kotlin/dislike/DislikeAnalyzer.kt
  material-color-utilities/src/main/kotlin/dynamiccolor/DynamicColor.kt
  material-color-utilities/src/main/kotlin/dynamiccolor/ToneDeltaConstraints.kt
  material-color-utilities/src/main/kotlin/dynamiccolor/TonePolarity.kt
  material-color-utilities/src/main/kotlin/hct/Cam16.kt
  material-color-utilities/src/main/kotlin/hct/Hct.kt
  material-color-utilities/src/main/kotlin/hct/HctSolver.kt
  material-color-utilities/src/main/kotlin/hct/ViewingConditions.kt
  material-color-utilities/src/main/kotlin/palettes/CorePalette.kt
  material-color-utilities/src/main/kotlin/palettes/TonalPalette.kt
  material-color-utilities/src/main/kotlin/quantize/PointProvider.kt
  material-color-utilities/src/main/kotlin/quantize/PointProviderLab.kt
  material-color-utilities/src/main/kotlin/quantize/Quantizer.kt
  material-color-utilities/src/main/kotlin/quantize/QuantizerCelebi.kt
  material-color-utilities/src/main/kotlin/quantize/QuantizerMap.kt
  material-color-utilities/src/main/kotlin/quantize/QuantizerResult.kt
  material-color-utilities/src/main/kotlin/quantize/QuantizerWsmeans.kt
  material-color-utilities/src/main/kotlin/quantize/QuantizerWu.kt
  material-color-utilities/src/main/kotlin/scheme/DynamicScheme.kt
  material-color-utilities/src/main/kotlin/scheme/Scheme.kt
  material-color-utilities/src/main/kotlin/scheme/SchemeContent.kt
  material-color-utilities/src/main/kotlin/scheme/SchemeExpressive.kt
  material-color-utilities/src/main/kotlin/scheme/SchemeFidelity.kt
  material-color-utilities/src/main/kotlin/scheme/SchemeMonochrome.kt
  material-color-utilities/src/main/kotlin/scheme/SchemeNeutral.kt
  material-color-utilities/src/main/kotlin/scheme/SchemeTonalSpot.kt
  material-color-utilities/src/main/kotlin/scheme/SchemeVibrant.kt
  material-color-utilities/src/main/kotlin/scheme/Variant.kt
  material-color-utilities/src/main/kotlin/score/Score.kt
  material-color-utilities/src/main/kotlin/temperature/TemperaturCache.kt
  material-color-utilities/src/main/kotlin/theme/Theme.kt
  material-color-utilities/src/main/kotlin/utils/ColorUtils.kt
  material-color-utilities/src/main/kotlin/utils/MathUtils.kt
  material-color-utilities/src/main/kotlin/utils/ThemeUtils.kt
  settings.gradle.kts
Labels: dependencies

#216 Upgrade to Coil 3
  app/build.gradle.kts
  app/src/main/kotlin/com/imashnake/animite/features/media/MediaPage.kt
  core/build.gradle.kts
  core/src/main/kotlin/com/imashnake/animite/core/extensions/ImageRequestExt.kt
  core/src/main/kotlin/com/imashnake/animite/core/ui/MediaSmall.kt
  gradle/libs.versions.toml
  profile/build.gradle.kts
  profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt
Labels: enhancement, dependencies

#230 Replace Pastelize with MaterialKolor APIs
  app/src/main/kotlin/com/imashnake/animite/dev/ext/ColorExt.kt
  app/src/main/kotlin/com/imashnake/animite/dev/ext/ColorSchemeExt.kt
  app/src/main/kotlin/com/imashnake/animite/features/home/HomeScreen.kt
  app/src/main/kotlin/com/imashnake/animite/features/media/MediaPage.kt
  app/src/main/kotlin/com/imashnake/animite/features/media/MediaThemeUtil.kt
  app/src/main/kotlin/com/imashnake/animite/features/theme/Color.kt
  app/src/main/kotlin/com/imashnake/animite/features/theme/Theme.kt
  core/src/main/kotlin/com/imashnake/animite/core/Constants.kt
  core/src/main/kotlin/com/imashnake/animite/core/ui/MediaSmall.kt
Labels: enhancement

#231 Added Banner Shader
  app/src/main/kotlin/com/imashnake/animite/features/home/HomeScreen.kt
  core/src/main/kotlin/com/imashnake/animite/core/ui/shaders/Ethereal.kt
Labels: enhancement

#232 Re: Create new `media` module
  app/build.gradle.kts
  app/src/main/kotlin/com/imashnake/animite/features/MainActivity.kt
  app/src/main/kotlin/com/imashnake/animite/features/home/HomeScreen.kt
  app/src/main/kotlin/com/imashnake/animite/features/searchbar/SearchFrontDrop.kt
  app/src/main/kotlin/com/imashnake/animite/features/theme/Theme.kt
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  core/src/main/kotlin/com/imashnake/animite/core/extensions/ModifierExt.kt
  media/build.gradle.kts
  media/src/main/AndroidManifest.xml
  media/src/main/kotlin/com/imashnake/animite/media/MediaPage.kt
  media/src/main/kotlin/com/imashnake/animite/media/MediaPageViewModel.kt
  media/src/main/kotlin/com/imashnake/animite/media/MediaThemeUtil.kt
  media/src/main/kotlin/com/imashnake/animite/media/MediaUiState.kt
  media/src/main/kotlin/com/imashnake/animite/media/ext/ColorSchemeExt.kt
  media/src/main/res/drawable/background.webp
  media/src/main/res/drawable/youtube.xml
  media/src/main/res/values/dimens.xml
  media/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: feature, gradle

#233 Navigate to `MediaPage` from `ProfileScreen`
  app/build.gradle.kts
  app/src/main/kotlin/com/imashnake/animite/features/MainActivity.kt
  app/src/main/kotlin/com/imashnake/animite/features/home/HomeScreen.kt
  media/build.gradle.kts
  media/src/main/kotlin/com/imashnake/animite/media/MediaPage.kt
  profile/build.gradle.kts
  profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Anime.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/tabs/ProfileTab.kt
Labels: enhancement

#237 No dimens for paddings
  core/src/main/kotlin/com/imashnake/animite/core/ui/Paddings.kt
  core/src/main/res/values/dimens.xml
Labels: enhancement

#238 Create ComingSoonScreen
  core/src/main/kotlin/com/imashnake/animite/core/ui/ComingSoonScreen.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt
  social/src/main/kotlin/com/imashnake/animite/social/SocialScreen.kt
Labels: enhancement

#235 Groundwork for searching for Anime titles using MyAnimeList
  api/anilist/src/main/kotlin/com/imashnake/animite/api/anilist/AnilistSearchRepository.kt
  api/mal/build.gradle.kts
  api/mal/src/main/kotlin/com/imashnake/animite/api/mal/data/MyAnimeListSearchRepository.kt
  api/mal/src/main/kotlin/com/imashnake/animite/api/mal/data/model/AnimeSearchResponse.kt
  api/mal/src/main/kotlin/com/imashnake/animite/api/mal/di/NetworkModule.kt
  app/build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement, feature
