Repository imashnake0/Animite, pull requests merged in 2025-03, with the labels that each got.

#283 Rewrite Inset Handling
  app/src/main/kotlin/com/imashnake/animite/features/MainActivity.kt
  app/src/main/kotlin/com/imashnake/animite/features/home/HomeScreen.kt
  app/src/main/kotlin/com/imashnake/animite/features/searchbar/SearchFab.kt
  app/src/main/kotlin/com/imashnake/animite/features/searchbar/SearchFrontDrop.kt
  core/src/main/kotlin/com/imashnake/animite/core/extensions/ModifierExt.kt
  core/src/main/kotlin/com/imashnake/animite/core/extensions/PaddingValuesExt.kt
  core/src/main/kotlin/com/imashnake/animite/core/ui/MediaSmall.kt
  core/src/main/kotlin/com/imashnake/animite/core/ui/layouts/BannerLayout.kt
  media/src/main/kotlin/com/imashnake/animite/media/MediaPage.kt
  navigation/src/main/kotlin/com/imashnake/animite/navigation/NavigationBar.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/tabs/About.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Favourites.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Media.kt
Labels: enhancement

#294 Steal `PaddingValuesExt`
  app/src/main/kotlin/com/imashnake/animite/features/MainActivity.kt
  app/src/main/kotlin/com/imashnake/animite/features/home/HomeScreen.kt
  app/src/main/kotlin/com/imashnake/animite/features/searchbar/SearchFrontDrop.kt
  core/src/main/kotlin/com/imashnake/animite/core/extensions/PaddingValuesExt.kt
  core/src/main/kotlin/com/imashnake/animite/core/ui/layouts/BannerLayout.kt
  media/src/main/kotlin/com/imashnake/animite/media/MediaPage.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/tabs/About.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Favourites.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Media.kt
Labels: enhancement

#298 Fix Login -> Explicitly Specify Action
  app/src/main/kotlin/com/imashnake/animite/features/MainActivity.kt
Labels: bug

#299 Profile Screen -> Fave Navigation
  profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Favourites.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/tabs/Media.kt
Labels: enhancement

#304 Home Screen -> Fix Start Padding in Landscape Mode
  app/src/main/kotlin/com/imashnake/animite/features/home/HomeScreen.kt
Labels: enhancement

#311 Logout Dropdown
  gradle/libs.versions.toml
  profile/build.gradle.kts
  profile/src/main/kotlin/com/imashnake/animite/profile/ProfileScreen.kt
  profile/src/main/kotlin/com/imashnake/animite/profile/ProfileViewModel.kt
  profile/src/main/res/values/strings.xml
Labels: feature
